
//ACTIONS FOR TODOS
export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const MARK_COMPLETE = 'MARK_COMPLETE';

//ACTION FOR USER AUTHENTICATION
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGOUT = "LOGOUT";

//QUOTES API
export const FETCH_QUOTES_REQUEST = "FETCH_QUOTES_REQUEST";
export const FETCH_QUOTES_SUCCESS = "FETCH_QUOTES_SUCCESS";

